name: Run PDF Table Extractor

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3  

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use Python 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the script
      - name: Execute Python script
        run: |
          python extract_bank_statement.py

      # Step 5: Upload the Excel output as an artifact
      - name: Upload Excel Output
        uses: actions/upload-artifact@v3
        with:
          name: extracted-tables
          path: ./output/*.xlsx  # Path to your Excel files
